### ISSUE TITLE
兄弟走好不送

### ISSUE THREAD

**Issue by estemomento** [John-L-Smith/REPORTS#1]
牢里记得多学学 Git 的使用

**Comment by zhhbstudio** [comment]
火钳

**Comment by livc** [comment]
xswl

**Comment by sunriseXu** [comment]
cxk 牛逼

**Comment by m4rdukkkkk** [comment]
火钳刘明

**Comment by 0x1y** [comment]
唉

**Comment by BlameDeng** [comment]
暴露了啊

**Comment by ksco** [comment]
又蠢又坏，说的就是你

**Comment by MAVERICKdesu** [comment]
学长牛逼，我即刻来计控学院楼求教

**Comment by normanwang23** [comment]
你传git像cxk

**Comment by M-Quadra** [comment]
上网不涉密，奠

**Comment by agzou** [comment]
go 语言推广大使

**Comment by lovedemo** [comment]
鞠躬

**Comment by qiweiview** [comment]
鞠躬

**Comment by Ubpa** [comment]
嘻嘻嘻

**Comment by yaeterirri** [comment]
你写代码像cxk。

**Comment by ruiq** [comment]
好好学习git吧。。。哎。。。

**Comment by Ubpa** [comment]
看来是不怎么会用 git 。。

**Comment by bbyouli** [comment]
鞠躬

**Comment by Erfdcn** [comment]
感谢ikun提供价值7位数的go实战源码包

**Comment by summer19940609** [comment]
鞠躬

**Comment by minimAluminiumalism** [comment]
认为代码是这位 John-L-Smith 泄露的人才是真正的不会用 Git。泄露与这位用户毫无关系。

**Comment by insoxin** [comment]
go语言推广大使

**Comment by SukkaW** [comment]
@minimAluminiumalism 看看他其它 Repo，你觉得他会用 Git？他 Repo 都把 GitHub 当网盘来使

**Comment by estemomento** [comment]
> 认为代码是这位 John-L-Smith 泄露的人才是真正的不会用 Git。泄露与这位用户毫无关系。

这个用户提供了用于初始化仓库的 GitHub 账号，只有两个可能：

1. 是这个用户本人泄露或协助泄露的
2. 是这个用户因为使用不慎而被真正的泄露者加以利用的

**Comment by minimAluminiumalism** [comment]
泄密者不是经验不足，而是太有经验了。

**Comment by estemomento** [comment]
> 泄密者不是经验不足，而是太有经验了。

git.config.user.name 和 git.config.user.email 两者缺一不可，除非泄密者将该账户的 E-Mail 拿到。

**Comment by minimAluminiumalism** [comment]
> @minimAluminiumalism 看看他其它 Repo，你觉得他会用 Git？他 Repo 都把 GitHub 当网盘来使

泄密者没有 git config，而是直接 Push 了 repo，为什么会有 John-L-Smith，如果你用过 Vultr 的服务器就明白了，我在说一遍，跟他没有任何关系，只是你们的乌龙。

**Comment by minimAluminiumalism** [comment]
> > 泄密者不是经验不足，而是太有经验了。
> 
> git.config.user.name 和 git.config.user.email 两者缺一不可，除非泄密者将该账户的 E-Mail 拿到。

我一样都不需要就可以用他的名字冒名顶替，你信吗？

**Comment by estemomento** [comment]
> > @minimAluminiumalism 看看他其它 Repo，你觉得他会用 Git？他 Repo 都把 GitHub 当网盘来使
> 
> 泄密者没有 git config，而是直接 Push 了 repo，为什么会有 John-L-Smith，如果你用过 Vultr 的服务器就明白了，我在说一遍，跟他没有任何关系，只是你们的乌龙。

那是怎样把 vultr 和这个账户关联起来的

**Comment by minimAluminiumalism** [comment]
什么都不用做，root 权限下，只要你事先没有 git config 就直接提交，一样会成功，名称显示就是这位用户的用户名，一般的 Vultr VPS 通过此方式提交的代码全部都是默认 John-L-Smith。

**Comment by estemomento** [comment]
> 什么都不用做，root 权限下，只要你事先没有 git config 就直接提交，一样会成功，名称显示就是这位用户的用户名，一般的 Vultr VPS 通过此方式提交的代码全部都是默认 John-L-Smith。

其实屑站真想追查出来人也可以，但是要找 GitHub 查 IP，找 vultr 查付款，大费周章，还不一定找的是对的人

**Comment by WANG-lp** [comment]
只要把git的config.email设置成 `root@vultr.guest`然后提交到github就会显示是这个人提交的,
复现:

[test_repo](https://github.com/WANG-lp/test)

**Comment by luofei2011** [comment]
辟谣了，这哥们就是背锅侠。。。
![](https://ws1.sinaimg.cn/large/006tNc79ly1g2boh8z9toj316q0k0n3c.jpg)
